svg_icons: 
  default: 'calendar-day|clock|layer-group|chart-bar|user-graduate|comment-dots'
  type: 'list'
  list_type: 'compact'

topic_list_author_avatar_size:
  default: 40
  type: enum
  choices:
    - 24
    - 32
    - 40
    - 48
    - 56
    - 64
  description:
    en: "Author avatar size in topic lists, in pixels."

topic_list_author_avatar_shape:
  default: 50%
  type: enum
  choices:
    - 50%
    - 8px
    - 0
  description:
    en: "Author avatar border radius in topic lists. 50% is circle, 8px is rounded, 0 is square."
