svg_icons: 
  default: 'calendar-day|clock|layer-group|chart-bar|user-graduate|comment-dots'
  type: 'list'
  list_type: 'compact'

topic_list_author_avatar_size:
  default: 40
  type: integer
  min: 24
  max: 64
  description:
    en: "Author avatar size in topic lists, in pixels."
    zh_CN: "主题列表中发帖人头像的大小，单位为像素。"

topic_list_author_avatar_shape:
  default: circle
  type: enum
  choices:
    - circle
    - rounded
    - square
  description:
    en: "Author avatar shape in topic lists."
    zh_CN: "主题列表中发帖人头像的形状。"
